### ISSUE TITLE
startup issue

### ISSUE THREAD

**Issue by bullda** [primasio/primas-api-sdk-js#2]
I write some test code:

```
var Primas = require('primas-sdk-nodejs');

var client = new Primas({
    address: "xxxx",
    passphrase: "xxxx"
});

client.Account.metadata({accountId: 'bullda'});
```

when I run `node app.js` it shows:

```
var client = new Primas({
             ^

TypeError: Primas is not a constructor
    at Object.<anonymous> (xxx/blockchain/primas/primas_analyzer/app.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)
```

My `node.js -v` is v10.8.0. I have already install primas-sdk-nodejs and put keystore folder in workspace.

**Comment by DarrenWonder** [comment]
@bullda this bug has fixed! please update your npm package now

**Comment by bullda** [comment]
@DarrenWonder 
Thanks for your help. It runs now. But return 502 issue.

`node app.js`

```
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.10.3 (Ubuntu)</center>
</body>
</html>
```
